---
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285
# Enable logging
logger:
# Enable Web server
<<: !include network.yaml

api:
  password: !secret ESP_API_PWD
ota:
  password: !secret ESP_OTA_PWD
time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: true
    name: "${plug_name}_button"

switch:
  - platform: gpio
    name: "${plug_name}_Relay"
    pin: GPIO14
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${plug_name}_LED_Blue"
    pin: GPIO1
    inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "${plug_name}_LED_Red"
    pin: GPIO13
    inverted: true
    restore_mode: ALWAYS_OFF
sensor:
  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${plug_name}_Uptime Sensor
