---
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285
# Enable logging
logger:
# Enable Web server
<<: !include network.yaml

api:
  password: !secret ESP_API_PWD
ota:
  password: !secret ESP_OTA_PWD
time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: true
    name: "${plug_name}_button"

switch:
  - platform: gpio
    name: "${plug_name}_Relay"
    pin: GPIO14
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${plug_name}_LED_Blue"
    pin: GPIO1
    inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "${plug_name}_LED_Red"
    pin: GPIO13
    inverted: true
    restore_mode: ALWAYS_OFF
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${plug_name}_Amperage"
      unit_of_measurement: A
    voltage:
      name: "${plug_name}_Voltage"
      unit_of_measurement: V
    power:
      name: "${plug_name}_Wattage"
      unit_of_measurement: W
      id: "${plug_name}_Wattage"
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${plug_name}_Total Daily Energy"
    power_id: "${plug_name}_Wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${plug_name}_Uptime Sensor
