---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret eleveation_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # packages:  !include_dir_named packages
  packages: !include_dir_named components/packages
# Show links to resources in log and frontend
zone: !include_dir_list components/zones

mqtt:
  broker: !secret mqttip

# Enables the frontend
frontend:
  themes: !include themes.yaml

panel_iframe:

  logviewer:
    title: logviewer
    icon: mdi:cellphone-text
    url: !secret LOG_address

  # influxdb:
  #   title: InfluxDB
  #   icon: mdi:chart-areaspline
  #   url: http://hassio.local:8888

  # nodered:
  #   title: Node-RED
  #   icon: mdi:sitemap
  #   url: http://hassio.local:1880

  grafana:
    title: Grafana
    icon: mdi:chart-areaspline
    url: !secret Graf_url

  motioneye:
    title: Motioneye
    icon: mdi:cctv
    url: http://hassio.local:8765

  pihole:
    title: pihole
    icon: mdi:mdi:block-helper
    url: http://hassio.local:4865

  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret IDE_address

logger:
  default: warn
  logs:
    pychromecast.socket_client: fatal

# Enables configuration UI
config:
  base_url: !secret fritz_base_url

http:
  # api_password: !secret HA_PW
  ip_ban_enabled: true
  login_attempts_threshold: 5
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

recorder:
  exclude:
    entities:
      - sun.sun    # Don't record sun data
      - sensor.date
      - sensor.time

system_health:

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret dks_api_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - temperature
      - cloud_cover
      - humidity
      - ozone

  - platform: version
    name: version_available
    source: hassio
    image: qemux86-64

  - platform: version
    name: version_current

  - platform: synologydsm
    host: !secret synology_ip
    username: !secret synology_username
    password: !secret synology_password
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - disk_status
      - disk_smart_status
      - disk_temp
      - network_down
      - volume_size_used
      - volume_size_total
      - cpu_system_load
      - cpu_user_load
      - cpu_other_load
      - volume_percentage_used
      - volume_device_type
      - volume_disk_temp_avg

  - platform: fritzbox_netmonitor

  - platform: fritzbox_callmonitor
    name: Phone
    username: !secret fritz_user
    password: !secret fritz_password
    phonebook: 0
    prefixes:
      - '+49'
      - '+4989'
      - '089'
      - '+352'

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

#  - platform: template
#    sensors: !include template/sensors.yaml

# Text to speech
tts:
  - platform: google

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_secret
  max_retries: 3
  default_measurement: state

knx:
#   expose:
#     - type: 2.002
#       entity_id: sensor.knx_day
#       address: '4/2/16'

# Cloud
cloud:

#   - platform: spotify
#     client_id: !secret spotify_id
#     client_secret: !secret spotify_secret

device_tracker:
  # - platform: unifi
  #   username: !secret unify_id
  #   password: !secret unify_secret
  #   site_id: !secret unify_siteid
  #   detection_time: 240
  #   verify_ssl: false

  - platform: fritz
    interval_seconds: 30
    # consider_home: 180

ios:
  push:
    categories:
      - name: 'rollo'
        identifier: 'rollo'
        actions:
          - identifier: 'STOP_ROLLO'
            title: 'Stop'
            destructive: true
            activationMode: 'background'
      - name: 'quiet'
        identifier: 'quiet'
        actions:
          - identifier: 'QUIET_DISABLE'
            title: 'Disable'
            activationMode: 'background'
      - name: 'lockdoor'
        identifier: 'lockdoor'
        actions:
          - identifier: 'LOCK_DOOR'
            title: 'Lock The Door'
            destructive: true
            activationMode: 'background'

group: !include_dir_merge_named group
automation: !include automations.yaml
script: !include scripts.yaml
