---
alias: wm_running
hide_entity: true
trigger:
  platform: state
  entity_id: binary_sensor.lave_linge
  to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.openclose_9
  state: 'off'
action:
  service: input_select.select_option
  data:
    entity_id: input_select.washing_machine
    option: 'Running'
