---
binary_sensor:
  - platform: mqtt
    name: Entree
    state_topic: "windows/contacts"
    payload_on: "22 - 0"
    payload_off: "22 - 1"
    device_class: door

  - platform: mqtt
    name: Reserve
    state_topic: "windows/contacts"
    payload_on: "23 - 0"
    payload_off: "23 - 1"
    device_class: window
  - platform: mqtt
    name: Garage
    state_topic: "windows/contacts"
    payload_on: "24 - 0"
    payload_off: "24 - 1"
    device_class: Garage_door
  - platform: mqtt
    name: Local Technique Porte
    state_topic: "windows/contacts"
    payload_on: "25 - 0"
    payload_off: "25 - 1"
    device_class: Door
  - platform: mqtt
    name: Local Technique Fenetre
    state_topic: "windows/contacts"
    payload_on: "26 - 0"
    payload_off: "26 - 1"
    device_class: window
  - platform: mqtt
    name: Garage Porte
    state_topic: "windows/contacts"
    payload_on: "27 - 0"
    payload_off: "27 - 1"
    device_class: Door
  - platform: mqtt
    name: Garage Fenetre
    state_topic: "windows/contacts"
    payload_on: "28 - 0"
    payload_off: "28 - 1"
    device_class: window

  ########

  - platform: mqtt
    name: Buro
    state_topic: "windows/contacts"
    payload_on: "29 - 0"
    payload_off: "29 - 1"
    device_class: window
  - platform: mqtt
    name: Living R
    state_topic: "windows/contacts"
    payload_on: "30 - 0"
    payload_off: "30 - 1"
    device_class: window
  - platform: mqtt
    name: Living L
    state_topic: "windows/contacts"
    payload_on: "31 - 0"
    payload_off: "31 - 1"
    device_class: window
  - platform: mqtt
    name: Cuisine LA
    state_topic: "windows/contacts"
    payload_on: "32 - 0"
    payload_off: "32 - 1"
    device_class: window
  - platform: mqtt
    name: Cuisinie LM
    state_topic: "windows/contacts"
    payload_on: "33 - 0"
    payload_off: "33 - 1"
    device_class: window
  - platform: mqtt
    name: Cuisinie RM
    state_topic: "windows/contacts"
    payload_on: "34 - 0"
    payload_off: "34 - 1"
    device_class: window
  - platform: mqtt
    name: Cuisinie RA
    state_topic: "windows/contacts"
    payload_on: "35 - 0"
    payload_off: "35 - 1"
    device_class: window

  ###################

  - platform: mqtt
    name: Chac Parents
    state_topic: "windows/contacts"
    payload_on: "36 - 0"
    payload_off: "36 - 1"
    device_class: window
  - platform: mqtt
    name: Chac av
    state_topic: "windows/contacts"
    payload_on: "37 - 0"
    payload_off: "37 - 1"
    device_class: window
  - platform: mqtt
    name: Chac ar
    state_topic: "windows/contacts"
    payload_on: "38 - 0"
    payload_off: "38 - 1"
    device_class: window
  - platform: mqtt
    name: SDB P
    state_topic: "windows/contacts"
    payload_on: "39 - 0"
    payload_off: "39 - 1"
    device_class: window

  ###### SABOTAGE######

  - platform: mqtt
    name: RDC AV
    state_topic: "windows/sabotage"
    payload_on: "41 - 0"
    payload_off: "41 - 1"
    device_class: problem
  - platform: mqtt
    name: RDC ARR
    state_topic: "windows/sabotage"
    payload_on: "42 - 0"
    payload_off: "42 - 1"
    device_class: problem
  - platform: mqtt
    name: 1er AV
    state_topic: "windows/sabotage"
    payload_on: "43 - 0"
    payload_off: "43 - 1"
    device_class: problem
  - platform: mqtt
    name: 1er ARR
    state_topic: "windows/sabotage"
    payload_on: "44 - 0"
    payload_off: "44 - 1"
    device_class: problem
  - platform: mqtt
    name: 2eme AV
    state_topic: "windows/sabotage"
    payload_on: "45 - 0"
    payload_off: "45 - 1"
    device_class: problem
  - platform: mqtt
    name: 2eme ARR
    state_topic: "windows/sabotage"
    payload_on: "46 - 0"
    payload_off: "46 - 1"
    device_class: problem
