---
trigger:
  platform: state
  entity_id: binary_sensor.lave_vaisaille
  to: 'off'
# condition:
#   condition: state
#   entity_id: binary_sensor.openclose_9
#   state: 'off'
action:
  service: input_select.select_option
  data:
    entity_id: input_select.dish_washer_status
    option: 'Idle'
