---
esphome:
  name: sonoff_viessmann
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret Wifi_SSID
  password: !secret Wifi_PWD
  manual_ip:
    static_ip: !secret esphome_viessmann_static_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1

# Enable logging
logger:
# Enable Web server
web_server:
  port: 80
# Enable Home Assistant API
api:
  password: !secret ESP_API_PWD
ota:
  password: !secret ESP_OTA_PWD
time:
  - platform: homeassistant
    id: homeassistant_time

#################################################
sensor:
  - platform: wifi_signal
    name: esphome_viessmann_wifi_signal
    update_interval: 10s
  - platform: uptime
    name: esphome_viessmann_uptime
  - platform: cse7766
    update_interval: 5s
    current:
      name: viessmann_current
    voltage:
      name: viessmann_voltage
    power:
      id: power
      name: viessmann_power

text_sensor:
  - platform: version
    name: esphome_viessmann_esphome_version
