---
substitutions:
  plug_name: switch_radio_parents
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "955"
  ip_address: !secret esphome_switch_radio_parents_static_ip

<<: !include includes/gosund_sp1.yaml