---
substitutions:
  plug_name: switch_dishwasher
  ip_address: !secret esphome_switch_dishwasher_static_ip

<<: !include includes/gosund_sp1.yaml

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: "${plug_name}_Amperage"
      unit_of_measurement: A
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 0.0
            - 10.4 -> 8.233
            - 0.2 -> 0.155

    voltage:
      name: "${plug_name}_Voltage"
      unit_of_measurement: V
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 619.5 -> 241.7
            - 611.9 -> 236.3

    power:
      name: "${plug_name}_Wattage"
      unit_of_measurement: W
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 2.0
            - 113.8 -> 21.2
            - 11450 -> 1960

      id: "${plug_name}_Wattage"
    change_mode_every: 4
    update_interval: 5s
  - platform: total_daily_energy
    name: "${plug_name}_Total Daily Energy"
    power_id: "${plug_name}_Wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: template
    name: Lave Vaisaille
    filters:
      - delayed_off: 20s
    lambda: |-
      return id(${plug_name}_Wattage).state > 5;
