---
substitutions:
  plug_name: switch_ventilation
  # Higher value gives lower watt readout
  current_res: "0.00226"
  # Lower value gives lower voltage readout
  voltage_div: "930"
  ip_address: !secret esphome_switch_ventilation_static_ip

<<: !include includes/gosund_sp1.yaml

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: "${plug_name}_Amperage"
      unit_of_measurement: A
      filters:
        - calibrate_linear:
            #  # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 0.0
            - 10.4 -> 8.26

    voltage:
      name: "${plug_name}_Voltage"
      unit_of_measurement: V
      filters:
        - calibrate_linear:
            #    # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 0.0
            - 607.6 -> 241.1
            - 598.4 -> 237.5

    power:
      name: "${plug_name}_Wattage"
      unit_of_measurement: W
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 1.3
            - 113.8 -> 21.2
            - 11118 ->  1936

      id: "${plug_name}_Wattage"
    change_mode_every: 4
    update_interval: 2s
  - platform: total_daily_energy
    name: "${plug_name}_Total Daily Energy"
    power_id: "${plug_name}_Wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: template
    name: Ventitlation
    filters:
      - delayed_off: 10s
    lambda: |-
      return id(${plug_name}_Wattage).state > 5;
